name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm ci

    - name: Run lint
      if: ${{ always() }}
      run: |
        if [ -f package.json ] && grep -q "\"lint\"" package.json; then
          npm run lint --if-present;
        else
          echo "No lint script found, skipping";
        fi

    - name: Run tests
      run: |
        if [ -f package.json ] && grep -q "\"test\"" package.json; then
          npm test --if-present;
        else
          echo "No test script found, skipping";
        fi
